/* 
 * API dos Correios
 *
 * API de rastreios de Objetos Postais
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICEPApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Pesquisa pela faixa de CEPs nos municipios de um Estado.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Identificação do cliente usado na autenticação.</param>
        /// <param name="accessToken">Access token usado na autenticação.</param>
        /// <param name="estado">Abreviação do Estado.</param>
        /// <param name="municipio">Nome do Município. (optional)</param>
        /// <returns>List&lt;InlineResponse200&gt;</returns>
        List<InlineResponse200> CepEstadoGet (string clientId, string accessToken, string estado, string municipio = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Pesquisa pela faixa de CEPs nos municipios de um Estado.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Identificação do cliente usado na autenticação.</param>
        /// <param name="accessToken">Access token usado na autenticação.</param>
        /// <param name="estado">Abreviação do Estado.</param>
        /// <param name="municipio">Nome do Município. (optional)</param>
        /// <returns>ApiResponse of List&lt;InlineResponse200&gt;</returns>
        ApiResponse<List<InlineResponse200>> CepEstadoGetWithHttpInfo (string clientId, string accessToken, string estado, string municipio = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Pesquisa pela faixa de CEPs nos municipios de um Estado.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Identificação do cliente usado na autenticação.</param>
        /// <param name="accessToken">Access token usado na autenticação.</param>
        /// <param name="estado">Abreviação do Estado.</param>
        /// <param name="municipio">Nome do Município. (optional)</param>
        /// <returns>Task of List&lt;InlineResponse200&gt;</returns>
        System.Threading.Tasks.Task<List<InlineResponse200>> CepEstadoGetAsync (string clientId, string accessToken, string estado, string municipio = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Pesquisa pela faixa de CEPs nos municipios de um Estado.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Identificação do cliente usado na autenticação.</param>
        /// <param name="accessToken">Access token usado na autenticação.</param>
        /// <param name="estado">Abreviação do Estado.</param>
        /// <param name="municipio">Nome do Município. (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;InlineResponse200&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<InlineResponse200>>> CepEstadoGetAsyncWithHttpInfo (string clientId, string accessToken, string estado, string municipio = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CEPApi : ICEPApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CEPApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CEPApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CEPApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public CEPApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  Pesquisa pela faixa de CEPs nos municipios de um Estado.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Identificação do cliente usado na autenticação.</param>
        /// <param name="accessToken">Access token usado na autenticação.</param>
        /// <param name="estado">Abreviação do Estado.</param>
        /// <param name="municipio">Nome do Município. (optional)</param>
        /// <returns>List&lt;InlineResponse200&gt;</returns>
        public List<InlineResponse200> CepEstadoGet (string clientId, string accessToken, string estado, string municipio = null)
        {
             ApiResponse<List<InlineResponse200>> localVarResponse = CepEstadoGetWithHttpInfo(clientId, accessToken, estado, municipio);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Pesquisa pela faixa de CEPs nos municipios de um Estado.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Identificação do cliente usado na autenticação.</param>
        /// <param name="accessToken">Access token usado na autenticação.</param>
        /// <param name="estado">Abreviação do Estado.</param>
        /// <param name="municipio">Nome do Município. (optional)</param>
        /// <returns>ApiResponse of List&lt;InlineResponse200&gt;</returns>
        public ApiResponse< List<InlineResponse200> > CepEstadoGetWithHttpInfo (string clientId, string accessToken, string estado, string municipio = null)
        {
            // verify the required parameter 'clientId' is set
            if (clientId == null)
                throw new ApiException(400, "Missing required parameter 'clientId' when calling CEPApi->CepEstadoGet");
            // verify the required parameter 'accessToken' is set
            if (accessToken == null)
                throw new ApiException(400, "Missing required parameter 'accessToken' when calling CEPApi->CepEstadoGet");
            // verify the required parameter 'estado' is set
            if (estado == null)
                throw new ApiException(400, "Missing required parameter 'estado' when calling CEPApi->CepEstadoGet");

            var localVarPath = "/cep/{estado}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (estado != null) localVarPathParams.Add("estado", Configuration.ApiClient.ParameterToString(estado)); // path parameter
            if (municipio != null) localVarQueryParams.Add("municipio", Configuration.ApiClient.ParameterToString(municipio)); // query parameter
            if (clientId != null) localVarHeaderParams.Add("client_id", Configuration.ApiClient.ParameterToString(clientId)); // header parameter
            if (accessToken != null) localVarHeaderParams.Add("access_token", Configuration.ApiClient.ParameterToString(accessToken)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CepEstadoGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<InlineResponse200>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<InlineResponse200>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<InlineResponse200>)));
            
        }

        /// <summary>
        ///  Pesquisa pela faixa de CEPs nos municipios de um Estado.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Identificação do cliente usado na autenticação.</param>
        /// <param name="accessToken">Access token usado na autenticação.</param>
        /// <param name="estado">Abreviação do Estado.</param>
        /// <param name="municipio">Nome do Município. (optional)</param>
        /// <returns>Task of List&lt;InlineResponse200&gt;</returns>
        public async System.Threading.Tasks.Task<List<InlineResponse200>> CepEstadoGetAsync (string clientId, string accessToken, string estado, string municipio = null)
        {
             ApiResponse<List<InlineResponse200>> localVarResponse = await CepEstadoGetAsyncWithHttpInfo(clientId, accessToken, estado, municipio);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Pesquisa pela faixa de CEPs nos municipios de um Estado.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Identificação do cliente usado na autenticação.</param>
        /// <param name="accessToken">Access token usado na autenticação.</param>
        /// <param name="estado">Abreviação do Estado.</param>
        /// <param name="municipio">Nome do Município. (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;InlineResponse200&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<InlineResponse200>>> CepEstadoGetAsyncWithHttpInfo (string clientId, string accessToken, string estado, string municipio = null)
        {
            // verify the required parameter 'clientId' is set
            if (clientId == null)
                throw new ApiException(400, "Missing required parameter 'clientId' when calling CEPApi->CepEstadoGet");
            // verify the required parameter 'accessToken' is set
            if (accessToken == null)
                throw new ApiException(400, "Missing required parameter 'accessToken' when calling CEPApi->CepEstadoGet");
            // verify the required parameter 'estado' is set
            if (estado == null)
                throw new ApiException(400, "Missing required parameter 'estado' when calling CEPApi->CepEstadoGet");

            var localVarPath = "/cep/{estado}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (estado != null) localVarPathParams.Add("estado", Configuration.ApiClient.ParameterToString(estado)); // path parameter
            if (municipio != null) localVarQueryParams.Add("municipio", Configuration.ApiClient.ParameterToString(municipio)); // query parameter
            if (clientId != null) localVarHeaderParams.Add("client_id", Configuration.ApiClient.ParameterToString(clientId)); // header parameter
            if (accessToken != null) localVarHeaderParams.Add("access_token", Configuration.ApiClient.ParameterToString(accessToken)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CepEstadoGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<InlineResponse200>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<InlineResponse200>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<InlineResponse200>)));
            
        }

    }
}
