/*
 * API do Futebolcard
 * Futebolcard manipulation API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * InlineResponse2002Subsectors
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-22T17:08:03.639Z")
public class InlineResponse2002Subsectors {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("hasTicket")
  private Integer hasTicket = null;

  public InlineResponse2002Subsectors id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "831318", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public InlineResponse2002Subsectors name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "S05", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse2002Subsectors hasTicket(Integer hasTicket) {
    this.hasTicket = hasTicket;
    return this;
  }

   /**
   * Get hasTicket
   * @return hasTicket
  **/
  @ApiModelProperty(example = "1", value = "")
  public Integer getHasTicket() {
    return hasTicket;
  }

  public void setHasTicket(Integer hasTicket) {
    this.hasTicket = hasTicket;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002Subsectors inlineResponse2002Subsectors = (InlineResponse2002Subsectors) o;
    return Objects.equals(this.id, inlineResponse2002Subsectors.id) &&
        Objects.equals(this.name, inlineResponse2002Subsectors.name) &&
        Objects.equals(this.hasTicket, inlineResponse2002Subsectors.hasTicket);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, hasTicket);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002Subsectors {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    hasTicket: ").append(toIndentedString(hasTicket)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

