/*
 * API do Futebolcard
 * Futebolcard manipulation API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse2001Map;
import io.swagger.client.model.InlineResponse2002Subsectors;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse2002
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-22T17:08:03.639Z")
public class InlineResponse2002 {
  @SerializedName("subsectors")
  private List<InlineResponse2002Subsectors> subsectors = new ArrayList<InlineResponse2002Subsectors>();

  @SerializedName("map")
  private List<InlineResponse2001Map> map = new ArrayList<InlineResponse2001Map>();

  public InlineResponse2002 subsectors(List<InlineResponse2002Subsectors> subsectors) {
    this.subsectors = subsectors;
    return this;
  }

  public InlineResponse2002 addSubsectorsItem(InlineResponse2002Subsectors subsectorsItem) {
    this.subsectors.add(subsectorsItem);
    return this;
  }

   /**
   * Get subsectors
   * @return subsectors
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<InlineResponse2002Subsectors> getSubsectors() {
    return subsectors;
  }

  public void setSubsectors(List<InlineResponse2002Subsectors> subsectors) {
    this.subsectors = subsectors;
  }

  public InlineResponse2002 map(List<InlineResponse2001Map> map) {
    this.map = map;
    return this;
  }

  public InlineResponse2002 addMapItem(InlineResponse2001Map mapItem) {
    this.map.add(mapItem);
    return this;
  }

   /**
   * Get map
   * @return map
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<InlineResponse2001Map> getMap() {
    return map;
  }

  public void setMap(List<InlineResponse2001Map> map) {
    this.map = map;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002 inlineResponse2002 = (InlineResponse2002) o;
    return Objects.equals(this.subsectors, inlineResponse2002.subsectors) &&
        Objects.equals(this.map, inlineResponse2002.map);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subsectors, map);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002 {\n");
    
    sb.append("    subsectors: ").append(toIndentedString(subsectors)).append("\n");
    sb.append("    map: ").append(toIndentedString(map)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

