# coding: utf-8

"""
    API dos Correios

    API de rastreios de Objetos Postais

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.eventos import Eventos


class TestEventos(unittest.TestCase):
    """ Eventos unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventos(self):
        """
        Test Eventos
        """
        model = swagger_client.models.eventos.Eventos()


if __name__ == '__main__':
    unittest.main()
