# coding: utf-8

"""
    API dos Correios

    API de rastreios de Objetos Postais

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.erro import Erro


class TestErro(unittest.TestCase):
    """ Erro unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErro(self):
        """
        Test Erro
        """
        model = swagger_client.models.erro.Erro()


if __name__ == '__main__':
    unittest.main()
