# coding: utf-8

"""
    API dos Correios

    Postal Object tracking API

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.zipcode_range import ZipcodeRange


class TestZipcodeRange(unittest.TestCase):
    """ ZipcodeRange unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testZipcodeRange(self):
        """
        Test ZipcodeRange
        """
        model = swagger_client.models.zipcode_range.ZipcodeRange()


if __name__ == '__main__':
    unittest.main()
