/* 
 * API Agillitas Cartões Pré-pagos
 *
 * API para manipular recursos relacionadas à cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// CartaoDisponivel
    /// </summary>
    [DataContract]
    public partial class CartaoDisponivel :  IEquatable<CartaoDisponivel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CartaoDisponivel" /> class.
        /// </summary>
        /// <param name="IdCartao">Número identificador referente ao proxy do cartão..</param>
        public CartaoDisponivel(decimal? IdCartao = default(decimal?))
        {
            this.IdCartao = IdCartao;
        }
        
        /// <summary>
        /// Número identificador referente ao proxy do cartão.
        /// </summary>
        /// <value>Número identificador referente ao proxy do cartão.</value>
        [DataMember(Name="idCartao", EmitDefaultValue=false)]
        public decimal? IdCartao { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CartaoDisponivel {\n");
            sb.Append("  IdCartao: ").Append(IdCartao).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CartaoDisponivel);
        }

        /// <summary>
        /// Returns true if CartaoDisponivel instances are equal
        /// </summary>
        /// <param name="other">Instance of CartaoDisponivel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CartaoDisponivel other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.IdCartao == other.IdCartao ||
                    this.IdCartao != null &&
                    this.IdCartao.Equals(other.IdCartao)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.IdCartao != null)
                    hash = hash * 59 + this.IdCartao.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
