=begin
#API Agillitas Cartões Pré-pagos

#API para manipular recursos relacionadas à cartões pré-pagos Agillitas.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CartoesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CartoesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CartoesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CartoesApi' do
    it 'should create an instact of CartoesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CartoesApi)
    end
  end

  # unit tests for cartoes_get
  # Obtém o número de identificação (Proxy) de um cartão
  # &lt;p&gt;Permite a verificação de disponibilidade de cartão e qual o número de identificação (Proxy) para posterior requisição.&lt;/p&gt;&lt;br/&gt;&lt;p class&#x3D;&#39;obs obs-danger&#39;&gt; Este recurso só poderá ser utilizado em produção mediante aprovação.&lt;/p&gt;
  # @param tipo_cartao Identifica qual o tipo do cartão, físico ou virtual.
  # @param [Hash] opts the optional parameters
  # @return [CartaoDisponivel]
  describe 'cartoes_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cartoes_id_cartao_extrato_get
  # Extrato do cartão
  # &lt;p&gt;Permite a consulta dos movimentos por período, de um determinado cartão. A janela máxima de observação é de 30 dias, e as datas inicial e final de observação pode ser configuradas, conforme necessidade.&lt;/p&gt;
  # @param id_cartao Número identificador referente ao proxy localizado no verso do cartão.
  # @param data_inicial Data inicial para a consulta.
  # @param data_final Data final para a consulta.
  # @param [Hash] opts the optional parameters
  # @return [ExtratoResponse]
  describe 'cartoes_id_cartao_extrato_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cartoes_id_cartao_portador_get
  # Informações do portador do cartão
  # &lt;p&gt;Permite a consulta de informações cadastrais de um determinado portador de cartão.&lt;/p&gt;
  # @param id_cartao Número identificador referente ao proxy localizado no verso do cartão.
  # @param [Hash] opts the optional parameters
  # @return [PortadorResponse]
  describe 'cartoes_id_cartao_portador_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cartoes_id_cartao_saldo_get
  # Saldo do cartão
  # &lt;p&gt;Permite a consulta do saldo disponível de um determinado cartão.&lt;/p&gt;
  # @param id_cartao Número identificador referente ao proxy localizado no verso do cartão.
  # @param [Hash] opts the optional parameters
  # @return [Saldo]
  describe 'cartoes_id_cartao_saldo_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cartoes_id_cartao_saldo_put
  # Credita ou debita valor da conta de um cartão.
  # &lt;p&gt;Permite creditar ou debitar um valor especifico em um determinado cartão.&lt;/p&gt;&lt;br/&gt;&lt;p class&#x3D;&#39;obs obs-danger&#39;&gt;Este recurso deve ser utilizado somente pelo reseller e quando o credito do cartão for de responsabilidade e propriedade do Reseller.&lt;/p&gt;
  # @param id_cartao Número identificador referente ao proxy localizado no verso do cartão.
  # @param saldo Objeto de requisição
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'cartoes_id_cartao_saldo_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cartoes_id_cartao_status_get
  # Status do cartão
  # &lt;p&gt;Permite a consulta do status de um determinado cartão. O status do cartão nos permite saber se o cartão esta ativo, bloqueado , desbloqueado ou cancelado.&lt;/p&gt;
  # @param id_cartao Número identificador referente ao proxy localizado no verso do cartão.
  # @param [Hash] opts the optional parameters
  # @return [StatusCartaoResponse]
  describe 'cartoes_id_cartao_status_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cartoes_id_cartao_status_put
  # Altera status do cartão
  # &lt;p&gt;Permite o bloqueio e desbloqueio de um determinado cartão.&lt;/p&gt;
  # @param id_cartao Número identificador referente ao proxy localizado no verso do cartão.
  # @param status Objeto de requisição
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'cartoes_id_cartao_status_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cartoes_post
  # Requisita um cartão de debito
  # &lt;p&gt;Permite a carga de um valor especifico a um determinado cartão.&lt;/p&gt;&lt;br/&gt;&lt;p class&#x3D;&#39;obs obs-danger&#39;&gt;Este recurso deve ser utilizado somente pelo reseller e com fundo disponível na conta e ainda dependente de aprovação pelo agente financeiro&lt;/p&gt; 
  # @param cartao Objeto de requisição
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'cartoes_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
