# coding: utf-8

"""
    API dos Correios

    API de rastreios de Objetos Postais

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ObjetoPostal(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, numero=None, eventos=None):
        """
        ObjetoPostal - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'numero': 'str',
            'eventos': 'list[ObjetosEventos]'
        }

        self.attribute_map = {
            'numero': 'numero',
            'eventos': 'eventos'
        }

        self._numero = numero
        self._eventos = eventos

    @property
    def numero(self):
        """
        Gets the numero of this ObjetoPostal.
        

        :return: The numero of this ObjetoPostal.
        :rtype: str
        """
        return self._numero

    @numero.setter
    def numero(self, numero):
        """
        Sets the numero of this ObjetoPostal.
        

        :param numero: The numero of this ObjetoPostal.
        :type: str
        """

        self._numero = numero

    @property
    def eventos(self):
        """
        Gets the eventos of this ObjetoPostal.

        :return: The eventos of this ObjetoPostal.
        :rtype: list[ObjetosEventos]
        """
        return self._eventos

    @eventos.setter
    def eventos(self, eventos):
        """
        Sets the eventos of this ObjetoPostal.

        :param eventos: The eventos of this ObjetoPostal.
        :type: list[ObjetosEventos]
        """

        self._eventos = eventos

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ObjetoPostal):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
