=begin
#API do Futebolcard

#Futebolcard manipulation API

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::EventseventIdsectorssectorIdsubsectorssubsectorIdSeats
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EventseventIdsectorssectorIdsubsectorssubsectorIdSeats' do
  before do
    # run before each test
    @instance = SwaggerClient::EventseventIdsectorssectorIdsubsectorssubsectorIdSeats.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EventseventIdsectorssectorIdsubsectorssubsectorIdSeats' do
    it 'should create an instact of EventseventIdsectorssectorIdsubsectorssubsectorIdSeats' do
      expect(@instance).to be_instance_of(SwaggerClient::EventseventIdsectorssectorIdsubsectorssubsectorIdSeats)
    end
  end
  describe 'test attribute "ticket_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "ticket_status"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "owner_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "seat_number"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

