=begin
#API do Futebolcard

#Futebolcard manipulation API

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::InlineResponse2002Subsectors
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InlineResponse2002Subsectors' do
  before do
    # run before each test
    @instance = SwaggerClient::InlineResponse2002Subsectors.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineResponse2002Subsectors' do
    it 'should create an instact of InlineResponse2002Subsectors' do
      expect(@instance).to be_instance_of(SwaggerClient::InlineResponse2002Subsectors)
    end
  end
  describe 'test attribute "subsector_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "has_tickets"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

