<?php
/**
 * CartoesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Agillitas Cartões Pré-pagos
 *
 * API para manipular recursos relacionadas à cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CartoesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CartoesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for cartoesGet
     *
     * Obtém o número de identificação (Proxy) de um cartão.
     *
     */
    public function testCartoesGet()
    {

    }

    /**
     * Test case for cartoesIdCartaoExtratoGet
     *
     * Extrato do cartão.
     *
     */
    public function testCartoesIdCartaoExtratoGet()
    {

    }

    /**
     * Test case for cartoesIdCartaoPortadorGet
     *
     * Informações do portador do cartão.
     *
     */
    public function testCartoesIdCartaoPortadorGet()
    {

    }

    /**
     * Test case for cartoesIdCartaoSaldoGet
     *
     * Saldo do cartão.
     *
     */
    public function testCartoesIdCartaoSaldoGet()
    {

    }

    /**
     * Test case for cartoesIdCartaoSaldoPut
     *
     * Credita ou debita valor da conta de um cartão..
     *
     */
    public function testCartoesIdCartaoSaldoPut()
    {

    }

    /**
     * Test case for cartoesIdCartaoStatusGet
     *
     * Status do cartão.
     *
     */
    public function testCartoesIdCartaoStatusGet()
    {

    }

    /**
     * Test case for cartoesIdCartaoStatusPut
     *
     * Altera status do cartão.
     *
     */
    public function testCartoesIdCartaoStatusPut()
    {

    }

    /**
     * Test case for cartoesPost
     *
     * Requisita um cartão de debito.
     *
     */
    public function testCartoesPost()
    {

    }

}
