/* 
 * API do Futebolcard
 *
 * Futebolcard manipulation API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Sectors
    /// </summary>
    [DataContract]
    public partial class Sectors :  IEquatable<Sectors>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Sectors" /> class.
        /// </summary>
        /// <param name="Gates">Gates.</param>
        /// <param name="Map">Map.</param>
        public Sectors(List<InlineResponse2001Gates> Gates = default(List<InlineResponse2001Gates>), List<InlineResponse2001Map> Map = default(List<InlineResponse2001Map>))
        {
            this.Gates = Gates;
            this.Map = Map;
        }
        
        /// <summary>
        /// Gets or Sets Gates
        /// </summary>
        [DataMember(Name="gates", EmitDefaultValue=false)]
        public List<InlineResponse2001Gates> Gates { get; set; }
        /// <summary>
        /// Gets or Sets Map
        /// </summary>
        [DataMember(Name="map", EmitDefaultValue=false)]
        public List<InlineResponse2001Map> Map { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Sectors {\n");
            sb.Append("  Gates: ").Append(Gates).Append("\n");
            sb.Append("  Map: ").Append(Map).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Sectors);
        }

        /// <summary>
        /// Returns true if Sectors instances are equal
        /// </summary>
        /// <param name="other">Instance of Sectors to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Sectors other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Gates == other.Gates ||
                    this.Gates != null &&
                    this.Gates.SequenceEqual(other.Gates)
                ) && 
                (
                    this.Map == other.Map ||
                    this.Map != null &&
                    this.Map.SequenceEqual(other.Map)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Gates != null)
                    hash = hash * 59 + this.Gates.GetHashCode();
                if (this.Map != null)
                    hash = hash * 59 + this.Map.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
