=begin
#API Agillitas Cartões Pré-pagos

#API para manipular recursos relacionadas à cartões pré-pagos Agillitas.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::ExtratoResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ExtratoResponse' do
  before do
    # run before each test
    @instance = SwaggerClient::ExtratoResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExtratoResponse' do
    it 'should create an instact of ExtratoResponse' do
      expect(@instance).to be_instance_of(SwaggerClient::ExtratoResponse)
    end
  end
  describe 'test attribute "extrato"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

