# coding: utf-8

"""
    API dos Correios

    API de rastreios de Objetos Postais

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.detalhes_eventos import DetalhesEventos
from .models.endereco import Endereco
from .models.erro import Erro
from .models.eventos import Eventos
from .models.faixa_cep import FaixaCEP
from .models.inline_response_200 import InlineResponse200
from .models.inline_response_200_1 import InlineResponse2001
from .models.inline_response_200_2 import InlineResponse2002
from .models.inline_response_200_3 import InlineResponse2003
from .models.inline_response_400 import InlineResponse400
from .models.objeto_postal import ObjetoPostal
from .models.objetos_eventos import ObjetosEventos

# import apis into sdk package
from .apis.cep_api import CEPApi
from .apis.enderecoes_api import EnderecoesApi
from .apis.objeto_postal_api import ObjetoPostalApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
