# coding: utf-8

"""
    API Agillitas Cartões Pré-pagos

    API para manipular recursos relacionadas à cartões pré-pagos Agillitas.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.cartoes_api import CartoesApi


class TestCartoesApi(unittest.TestCase):
    """ CartoesApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.cartoes_api.CartoesApi()

    def tearDown(self):
        pass

    def test_cartoes_get(self):
        """
        Test case for cartoes_get

        Obtém o número de identificação (Proxy) de um cartão
        """
        pass

    def test_cartoes_id_cartao_extrato_get(self):
        """
        Test case for cartoes_id_cartao_extrato_get

        Extrato do cartão
        """
        pass

    def test_cartoes_id_cartao_portador_get(self):
        """
        Test case for cartoes_id_cartao_portador_get

        Informações do portador do cartão
        """
        pass

    def test_cartoes_id_cartao_saldo_get(self):
        """
        Test case for cartoes_id_cartao_saldo_get

        Saldo do cartão
        """
        pass

    def test_cartoes_id_cartao_saldo_put(self):
        """
        Test case for cartoes_id_cartao_saldo_put

        Credita ou debita valor da conta de um cartão.
        """
        pass

    def test_cartoes_id_cartao_status_get(self):
        """
        Test case for cartoes_id_cartao_status_get

        Status do cartão
        """
        pass

    def test_cartoes_id_cartao_status_put(self):
        """
        Test case for cartoes_id_cartao_status_put

        Altera status do cartão
        """
        pass

    def test_cartoes_post(self):
        """
        Test case for cartoes_post

        Requisita um cartão de debito
        """
        pass


if __name__ == '__main__':
    unittest.main()
