/* 
 * API do Futebolcard
 *
 * Futebolcard manipulation API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Row
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RowTests
    {
        // TODO uncomment below to declare an instance variable for Row
        //private Row instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Row
            //instance = new Row();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Row
        /// </summary>
        [Test]
        public void RowInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Row
            //Assert.IsInstanceOfType<Row> (instance, "variable 'instance' is a Row");
        }

        /// <summary>
        /// Test the property 'RowId'
        /// </summary>
        [Test]
        public void RowIdTest()
        {
            // TODO unit test for the property 'RowId'
        }
        /// <summary>
        /// Test the property 'RowAlias'
        /// </summary>
        [Test]
        public void RowAliasTest()
        {
            // TODO unit test for the property 'RowAlias'
        }
        /// <summary>
        /// Test the property 'RowName'
        /// </summary>
        [Test]
        public void RowNameTest()
        {
            // TODO unit test for the property 'RowName'
        }
        /// <summary>
        /// Test the property 'Seats'
        /// </summary>
        [Test]
        public void SeatsTest()
        {
            // TODO unit test for the property 'Seats'
        }

    }

}
