/* 
 * API do Futebolcard
 *
 * Futebolcard manipulation API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Seat
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SeatTests
    {
        // TODO uncomment below to declare an instance variable for Seat
        //private Seat instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Seat
            //instance = new Seat();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Seat
        /// </summary>
        [Test]
        public void SeatInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Seat
            //Assert.IsInstanceOfType<Seat> (instance, "variable 'instance' is a Seat");
        }

        /// <summary>
        /// Test the property 'TicketId'
        /// </summary>
        [Test]
        public void TicketIdTest()
        {
            // TODO unit test for the property 'TicketId'
        }
        /// <summary>
        /// Test the property 'TicketStatus'
        /// </summary>
        [Test]
        public void TicketStatusTest()
        {
            // TODO unit test for the property 'TicketStatus'
        }
        /// <summary>
        /// Test the property 'OwnerId'
        /// </summary>
        [Test]
        public void OwnerIdTest()
        {
            // TODO unit test for the property 'OwnerId'
        }
        /// <summary>
        /// Test the property 'SeatNumber'
        /// </summary>
        [Test]
        public void SeatNumberTest()
        {
            // TODO unit test for the property 'SeatNumber'
        }

    }

}
