/* 
 * API do Futebolcard
 *
 * Futebolcard manipulation API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SubSectorDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubSectorDetailsTests
    {
        // TODO uncomment below to declare an instance variable for SubSectorDetails
        //private SubSectorDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubSectorDetails
            //instance = new SubSectorDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubSectorDetails
        /// </summary>
        [Test]
        public void SubSectorDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubSectorDetails
            //Assert.IsInstanceOfType<SubSectorDetails> (instance, "variable 'instance' is a SubSectorDetails");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'HasTicket'
        /// </summary>
        [Test]
        public void HasTicketTest()
        {
            // TODO unit test for the property 'HasTicket'
        }

    }

}
