/* 
 * API Agillitas Cartões Pré-pagos
 *
 * API para manipular recursos relacionadas à cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Valor
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ValorTests
    {
        // TODO uncomment below to declare an instance variable for Valor
        //private Valor instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Valor
            //instance = new Valor();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Valor
        /// </summary>
        [Test]
        public void ValorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Valor
            //Assert.IsInstanceOfType<Valor> (instance, "variable 'instance' is a Valor");
        }

        /// <summary>
        /// Test the property '_Valor'
        /// </summary>
        [Test]
        public void _ValorTest()
        {
            // TODO unit test for the property '_Valor'
        }

    }

}
