# coding: utf-8

"""
    API do Futebolcard

    Futebolcard manipulation API

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.eventsevent_idsectorssector_idsubsectorssubsector_id_seats import EventseventIdsectorssectorIdsubsectorssubsectorIdSeats


class TestEventseventIdsectorssectorIdsubsectorssubsectorIdSeats(unittest.TestCase):
    """ EventseventIdsectorssectorIdsubsectorssubsectorIdSeats unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventseventIdsectorssectorIdsubsectorssubsectorIdSeats(self):
        """
        Test EventseventIdsectorssectorIdsubsectorssubsectorIdSeats
        """
        model = swagger_client.models.eventsevent_idsectorssector_idsubsectorssubsector_id_seats.EventseventIdsectorssectorIdsubsectorssubsectorIdSeats()


if __name__ == '__main__':
    unittest.main()
