# coding: utf-8

"""
    API do Futebolcard

    Futebolcard manipulation API

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.inline_response_200_1_gates import InlineResponse2001Gates


class TestInlineResponse2001Gates(unittest.TestCase):
    """ InlineResponse2001Gates unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001Gates(self):
        """
        Test InlineResponse2001Gates
        """
        model = swagger_client.models.inline_response_200_1_gates.InlineResponse2001Gates()


if __name__ == '__main__':
    unittest.main()
