# coding: utf-8

"""
    API do Futebolcard

    Futebolcard manipulation API

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.sub_sectors import SubSectors


class TestSubSectors(unittest.TestCase):
    """ SubSectors unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubSectors(self):
        """
        Test SubSectors
        """
        model = swagger_client.models.sub_sectors.SubSectors()


if __name__ == '__main__':
    unittest.main()
