# coding: utf-8

"""
    API do Futebolcard

    Futebolcard manipulation API

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.coordinate import Coordinate


class TestCoordinate(unittest.TestCase):
    """ Coordinate unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCoordinate(self):
        """
        Test Coordinate
        """
        model = swagger_client.models.coordinate.Coordinate()


if __name__ == '__main__':
    unittest.main()
