/* 
 * API Agillitas Cartões Pré-pagos
 *
 * API para manipular recursos relacionadas à cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// SetTransferencia
    /// </summary>
    [DataContract]
    public partial class SetTransferencia :  IEquatable<SetTransferencia>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetTransferencia" /> class.
        /// </summary>
        /// <param name="IdCartao">Número identificador referente ao proxy do cartão origem de transferência..</param>
        /// <param name="IdCartaoDestino">Número identificador referente ao proxy do cartão destino de transferência..</param>
        /// <param name="Valor">Valor monetário a ser transferido..</param>
        /// <param name="Senha">Senha do cartão..</param>
        public SetTransferencia(decimal? IdCartao = default(decimal?), decimal? IdCartaoDestino = default(decimal?), double? Valor = default(double?), string Senha = default(string))
        {
            this.IdCartao = IdCartao;
            this.IdCartaoDestino = IdCartaoDestino;
            this.Valor = Valor;
            this.Senha = Senha;
        }
        
        /// <summary>
        /// Número identificador referente ao proxy do cartão origem de transferência.
        /// </summary>
        /// <value>Número identificador referente ao proxy do cartão origem de transferência.</value>
        [DataMember(Name="idCartao", EmitDefaultValue=false)]
        public decimal? IdCartao { get; set; }
        /// <summary>
        /// Número identificador referente ao proxy do cartão destino de transferência.
        /// </summary>
        /// <value>Número identificador referente ao proxy do cartão destino de transferência.</value>
        [DataMember(Name="idCartaoDestino", EmitDefaultValue=false)]
        public decimal? IdCartaoDestino { get; set; }
        /// <summary>
        /// Valor monetário a ser transferido.
        /// </summary>
        /// <value>Valor monetário a ser transferido.</value>
        [DataMember(Name="valor", EmitDefaultValue=false)]
        public double? Valor { get; set; }
        /// <summary>
        /// Senha do cartão.
        /// </summary>
        /// <value>Senha do cartão.</value>
        [DataMember(Name="senha", EmitDefaultValue=false)]
        public string Senha { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SetTransferencia {\n");
            sb.Append("  IdCartao: ").Append(IdCartao).Append("\n");
            sb.Append("  IdCartaoDestino: ").Append(IdCartaoDestino).Append("\n");
            sb.Append("  Valor: ").Append(Valor).Append("\n");
            sb.Append("  Senha: ").Append(Senha).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as SetTransferencia);
        }

        /// <summary>
        /// Returns true if SetTransferencia instances are equal
        /// </summary>
        /// <param name="other">Instance of SetTransferencia to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SetTransferencia other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.IdCartao == other.IdCartao ||
                    this.IdCartao != null &&
                    this.IdCartao.Equals(other.IdCartao)
                ) && 
                (
                    this.IdCartaoDestino == other.IdCartaoDestino ||
                    this.IdCartaoDestino != null &&
                    this.IdCartaoDestino.Equals(other.IdCartaoDestino)
                ) && 
                (
                    this.Valor == other.Valor ||
                    this.Valor != null &&
                    this.Valor.Equals(other.Valor)
                ) && 
                (
                    this.Senha == other.Senha ||
                    this.Senha != null &&
                    this.Senha.Equals(other.Senha)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.IdCartao != null)
                    hash = hash * 59 + this.IdCartao.GetHashCode();
                if (this.IdCartaoDestino != null)
                    hash = hash * 59 + this.IdCartaoDestino.GetHashCode();
                if (this.Valor != null)
                    hash = hash * 59 + this.Valor.GetHashCode();
                if (this.Senha != null)
                    hash = hash * 59 + this.Senha.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
