/* 
 * API Agillitas Cartões Pré-pagos
 *
 * API para manipular recursos relacionadas à cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// TransferenciaCadastroBenificiario
    /// </summary>
    [DataContract]
    public partial class TransferenciaCadastroBenificiario :  IEquatable<TransferenciaCadastroBenificiario>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransferenciaCadastroBenificiario" /> class.
        /// </summary>
        /// <param name="Beneficiario">Beneficiario.</param>
        public TransferenciaCadastroBenificiario(CadastroBenificiario Beneficiario = default(CadastroBenificiario))
        {
            this.Beneficiario = Beneficiario;
        }
        
        /// <summary>
        /// Gets or Sets Beneficiario
        /// </summary>
        [DataMember(Name="beneficiario", EmitDefaultValue=false)]
        public CadastroBenificiario Beneficiario { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransferenciaCadastroBenificiario {\n");
            sb.Append("  Beneficiario: ").Append(Beneficiario).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as TransferenciaCadastroBenificiario);
        }

        /// <summary>
        /// Returns true if TransferenciaCadastroBenificiario instances are equal
        /// </summary>
        /// <param name="other">Instance of TransferenciaCadastroBenificiario to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransferenciaCadastroBenificiario other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Beneficiario == other.Beneficiario ||
                    this.Beneficiario != null &&
                    this.Beneficiario.Equals(other.Beneficiario)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Beneficiario != null)
                    hash = hash * 59 + this.Beneficiario.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
