/* 
 * API Agillitas Cartões Pré-pagos
 *
 * API para manipular recursos relacionadas à cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Valor
    /// </summary>
    [DataContract]
    public partial class Valor :  IEquatable<Valor>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Valor" /> class.
        /// </summary>
        /// <param name="_Valor">Valor monetário do saldo do cartão..</param>
        public Valor(double? _Valor = default(double?))
        {
            this._Valor = _Valor;
        }
        
        /// <summary>
        /// Valor monetário do saldo do cartão.
        /// </summary>
        /// <value>Valor monetário do saldo do cartão.</value>
        [DataMember(Name="valor", EmitDefaultValue=false)]
        public double? _Valor { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Valor {\n");
            sb.Append("  _Valor: ").Append(_Valor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Valor);
        }

        /// <summary>
        /// Returns true if Valor instances are equal
        /// </summary>
        /// <param name="other">Instance of Valor to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Valor other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this._Valor == other._Valor ||
                    this._Valor != null &&
                    this._Valor.Equals(other._Valor)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this._Valor != null)
                    hash = hash * 59 + this._Valor.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
