/**
 * API dos Correios
 * API de rastreios de Objetos Postais
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Customer Model
 **/
@ApiModel(description = "Customer Model")
public class InlineResponse2001 {
  
  @SerializedName("logradouro")
  private String logradouro = null;
  @SerializedName("bairro")
  private String bairro = null;
  @SerializedName("municipio")
  private String municipio = null;
  @SerializedName("uf")
  private String uf = null;

  /**
   * Nome do logradouro
   **/
  @ApiModelProperty(value = "Nome do logradouro")
  public String getLogradouro() {
    return logradouro;
  }
  public void setLogradouro(String logradouro) {
    this.logradouro = logradouro;
  }

  /**
   * Nome do Bairro
   **/
  @ApiModelProperty(value = "Nome do Bairro")
  public String getBairro() {
    return bairro;
  }
  public void setBairro(String bairro) {
    this.bairro = bairro;
  }

  /**
   * Nome do municipio
   **/
  @ApiModelProperty(value = "Nome do municipio")
  public String getMunicipio() {
    return municipio;
  }
  public void setMunicipio(String municipio) {
    this.municipio = municipio;
  }

  /**
   * Estado
   **/
  @ApiModelProperty(value = "Estado")
  public String getUf() {
    return uf;
  }
  public void setUf(String uf) {
    this.uf = uf;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return (this.logradouro == null ? inlineResponse2001.logradouro == null : this.logradouro.equals(inlineResponse2001.logradouro)) &&
        (this.bairro == null ? inlineResponse2001.bairro == null : this.bairro.equals(inlineResponse2001.bairro)) &&
        (this.municipio == null ? inlineResponse2001.municipio == null : this.municipio.equals(inlineResponse2001.municipio)) &&
        (this.uf == null ? inlineResponse2001.uf == null : this.uf.equals(inlineResponse2001.uf));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.logradouro == null ? 0: this.logradouro.hashCode());
    result = 31 * result + (this.bairro == null ? 0: this.bairro.hashCode());
    result = 31 * result + (this.municipio == null ? 0: this.municipio.hashCode());
    result = 31 * result + (this.uf == null ? 0: this.uf.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("  logradouro: ").append(logradouro).append("\n");
    sb.append("  bairro: ").append(bairro).append("\n");
    sb.append("  municipio: ").append(municipio).append("\n");
    sb.append("  uf: ").append(uf).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
