/**
 * API dos Correios
 * Postal Object tracking API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Customer Model
 **/
@ApiModel(description = "Customer Model")
public class InlineResponse2001 {
  
  @SerializedName("street")
  private String street = null;
  @SerializedName("neighborhood")
  private String neighborhood = null;
  @SerializedName("county")
  private String county = null;
  @SerializedName("state")
  private String state = null;

  /**
   * Street's name.
   **/
  @ApiModelProperty(value = "Street's name.")
  public String getStreet() {
    return street;
  }
  public void setStreet(String street) {
    this.street = street;
  }

  /**
   * Neighborhood name.
   **/
  @ApiModelProperty(value = "Neighborhood name.")
  public String getNeighborhood() {
    return neighborhood;
  }
  public void setNeighborhood(String neighborhood) {
    this.neighborhood = neighborhood;
  }

  /**
   * County's name.
   **/
  @ApiModelProperty(value = "County's name.")
  public String getCounty() {
    return county;
  }
  public void setCounty(String county) {
    this.county = county;
  }

  /**
   * State's abbreviation.
   **/
  @ApiModelProperty(value = "State's abbreviation.")
  public String getState() {
    return state;
  }
  public void setState(String state) {
    this.state = state;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return (this.street == null ? inlineResponse2001.street == null : this.street.equals(inlineResponse2001.street)) &&
        (this.neighborhood == null ? inlineResponse2001.neighborhood == null : this.neighborhood.equals(inlineResponse2001.neighborhood)) &&
        (this.county == null ? inlineResponse2001.county == null : this.county.equals(inlineResponse2001.county)) &&
        (this.state == null ? inlineResponse2001.state == null : this.state.equals(inlineResponse2001.state));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.street == null ? 0: this.street.hashCode());
    result = 31 * result + (this.neighborhood == null ? 0: this.neighborhood.hashCode());
    result = 31 * result + (this.county == null ? 0: this.county.hashCode());
    result = 31 * result + (this.state == null ? 0: this.state.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("  street: ").append(street).append("\n");
    sb.append("  neighborhood: ").append(neighborhood).append("\n");
    sb.append("  county: ").append(county).append("\n");
    sb.append("  state: ").append(state).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
