=begin
#API dos Correios

#API de rastreios de Objetos Postais

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::Erro
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Erro' do
  before do
    # run before each test
    @instance = SwaggerClient::Erro.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Erro' do
    it 'should create an instact of Erro' do
      expect(@instance).to be_instance_of(SwaggerClient::Erro)
    end
  end
  describe 'test attribute "resultado"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "detalhes"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

