/* 
 * API Agillitas Cartões Pré-pagos
 *
 * API para manipular recursos relacionadas à cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NovoCartaoPortadorEndereco
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NovoCartaoPortadorEnderecoTests
    {
        // TODO uncomment below to declare an instance variable for NovoCartaoPortadorEndereco
        //private NovoCartaoPortadorEndereco instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NovoCartaoPortadorEndereco
            //instance = new NovoCartaoPortadorEndereco();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NovoCartaoPortadorEndereco
        /// </summary>
        [Test]
        public void NovoCartaoPortadorEnderecoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NovoCartaoPortadorEndereco
            //Assert.IsInstanceOfType<NovoCartaoPortadorEndereco> (instance, "variable 'instance' is a NovoCartaoPortadorEndereco");
        }

        /// <summary>
        /// Test the property 'Logradouro'
        /// </summary>
        [Test]
        public void LogradouroTest()
        {
            // TODO unit test for the property 'Logradouro'
        }
        /// <summary>
        /// Test the property 'Complemento'
        /// </summary>
        [Test]
        public void ComplementoTest()
        {
            // TODO unit test for the property 'Complemento'
        }
        /// <summary>
        /// Test the property 'Cidade'
        /// </summary>
        [Test]
        public void CidadeTest()
        {
            // TODO unit test for the property 'Cidade'
        }
        /// <summary>
        /// Test the property 'Estado'
        /// </summary>
        [Test]
        public void EstadoTest()
        {
            // TODO unit test for the property 'Estado'
        }
        /// <summary>
        /// Test the property 'Pais'
        /// </summary>
        [Test]
        public void PaisTest()
        {
            // TODO unit test for the property 'Pais'
        }
        /// <summary>
        /// Test the property 'CodigoPostal'
        /// </summary>
        [Test]
        public void CodigoPostalTest()
        {
            // TODO unit test for the property 'CodigoPostal'
        }

    }

}
