/* 
 * API Agillitas Cartões Pré-pagos
 *
 * API para manipular recursos relacionadas à cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SetSaldoValor
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SetSaldoValorTests
    {
        // TODO uncomment below to declare an instance variable for SetSaldoValor
        //private SetSaldoValor instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SetSaldoValor
            //instance = new SetSaldoValor();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SetSaldoValor
        /// </summary>
        [Test]
        public void SetSaldoValorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SetSaldoValor
            //Assert.IsInstanceOfType<SetSaldoValor> (instance, "variable 'instance' is a SetSaldoValor");
        }

        /// <summary>
        /// Test the property 'Valor'
        /// </summary>
        [Test]
        public void ValorTest()
        {
            // TODO unit test for the property 'Valor'
        }

    }

}
