/**
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas à cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.DetalhamentoExtrato;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ExtratoResponse {
  
  @SerializedName("extrato")
  private List<DetalhamentoExtrato> extrato = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<DetalhamentoExtrato> getExtrato() {
    return extrato;
  }
  public void setExtrato(List<DetalhamentoExtrato> extrato) {
    this.extrato = extrato;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtratoResponse extratoResponse = (ExtratoResponse) o;
    return (this.extrato == null ? extratoResponse.extrato == null : this.extrato.equals(extratoResponse.extrato));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.extrato == null ? 0: this.extrato.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtratoResponse {\n");
    
    sb.append("  extrato: ").append(extrato).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
