# coding: utf-8

"""
    API Agillitas Cartões Pré-pagos

    API para manipular recursos relacionadas à cartões pré-pagos Agillitas.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.saldo import Saldo


class TestSaldo(unittest.TestCase):
    """ Saldo unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSaldo(self):
        """
        Test Saldo
        """
        model = swagger_client.models.saldo.Saldo()


if __name__ == '__main__':
    unittest.main()
